# GitHub Actions iOS Build - Direct Device Installation
# Builds iOS app without App Store Connect requirement

name: Build iOS App

# Trigger build on push to main branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    # Checkout repository code
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    # Install Flutter dependencies first
    - name: Install Flutter Dependencies
      run: flutter pub get
      
    # Clean and regenerate Flutter iOS configuration
    - name: Clean and Regenerate Flutter iOS Config
      run: |
        flutter clean
        flutter pub get
        
    # Install iOS CocoaPods dependencies
    - name: Install iOS Dependencies
      run: |
        cd ios
        pod install --verbose
        cd ..
        
    # Build iOS app
    - name: Build iOS App
      run: |
        flutter build ios --release --no-codesign
        
    # Create IPA file
    - name: Create IPA File
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ProcreateHelperWidget.ipa Payload/
        
    # Upload IPA as artifact
    - name: Upload IPA File
      uses: actions/upload-artifact@v4
      with:
        name: ProcreateHelperWidget-iOS
        path: build/ios/iphoneos/ProcreateHelperWidget.ipa
        retention-days: 30
        
    # Upload Runner.app for direct installation
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: ProcreateHelperWidget-App
        path: build/ios/iphoneos/Runner.app
        retention-days: 30