# GitHub Actions iOS Build - Direct Device Installation
# Builds iOS app without App Store Connect requirement

name: Build iOS App

# Trigger build on push to main branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    # Checkout repository code
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    # Install Flutter dependencies first
    - name: Install Flutter Dependencies
      run: flutter pub get
      
    # Clean and regenerate Flutter iOS configuration
    - name: Clean and Regenerate Flutter iOS Config
      run: |
        flutter clean
        flutter pub get
        
    # Install iOS CocoaPods dependencies
    - name: Install iOS Dependencies
      run: |
        cd ios
        pod install --verbose
        cd ..
        
    # Build iOS app for simulator (no signing required)
    - name: Build iOS App for Simulator
      run: |
        flutter build ios --simulator --debug
        
    # Build iOS app for device (attempt without signing)
    - name: Build iOS App for Device (Unsigned)
      run: |
        # Try building for device, but don't fail if it doesn't work
        flutter build ios --release --no-codesign || echo "Device build failed - continuing with simulator build"
        
    # Create IPA files
    - name: Create App Packages
      run: |
        # Create simulator IPA
        if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
          cd build/ios/iphonesimulator
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ProcreateHelperWidget-Simulator.ipa Payload/
          cd ../../..
        fi
        
        # Create device IPA if device build succeeded
        if [ -d "build/ios/iphoneos/Runner.app" ]; then
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ProcreateHelperWidget-Device.ipa Payload/
          cd ../../..
        fi
        
        # List what we created
        find build -name "*.ipa" -type f
        
    # Upload IPA files as artifacts
    - name: Upload App Packages
      uses: actions/upload-artifact@v4
      with:
        name: ProcreateHelperWidget-iOS-Apps
        path: |
          build/ios/iphonesimulator/ProcreateHelperWidget-Simulator.ipa
          build/ios/iphoneos/ProcreateHelperWidget-Device.ipa
        retention-days: 30
        if-no-files-found: ignore
        
    # Upload app bundles as backup
    - name: Upload App Bundles
      uses: actions/upload-artifact@v4
      with:
        name: ProcreateHelperWidget-App-Bundles
        path: |
          build/ios/iphonesimulator/Runner.app
          build/ios/iphoneos/Runner.app
        retention-days: 30
        if-no-files-found: ignore