# GitHub Actions iOS Build - Direct Device Installation
# Builds iOS app without App Store Connect requirement

name: Build iOS App

# Trigger build on push to main branch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    # Checkout repository code
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    # Install Flutter dependencies first
    - name: Install Flutter Dependencies
      run: flutter pub get
      
    # Clean and regenerate Flutter iOS configuration
    - name: Clean and Regenerate Flutter iOS Config
      run: |
        flutter clean
        flutter pub get
        
    # Fix Xcode project configuration issues
    - name: Fix Widget Extension Build Configuration
      run: |
        cd ios
        
        # The error occurs because Info.plist is in both:
        # 1. Copy Bundle Resources build phase (wrong)
        # 2. Process Info.plist build phase (correct)
        # We need to remove it from Copy Bundle Resources
        
        # Create a simple fix script
        cat > fix_project.py << 'EOF'
import re

# Read the project file
with open('Runner.xcodeproj/project.pbxproj', 'r') as f:
    content = f.read()

# Count occurrences before fix
before_count = content.count('ProcreateHelperWidget/Info.plist')
print(f"Found {before_count} references to ProcreateHelperWidget/Info.plist")

# Remove the line that contains ProcreateHelperWidget/Info.plist from Copy Bundle Resources
# This is typically a line like: 1234567890ABCDEF /* Info.plist */ = {isa = PBXFileReference; ...
lines = content.split('\n')
new_lines = []
removed_lines = 0

for line in lines:
    # Skip lines that are file references to the widget Info.plist in Copy Bundle Resources
    if 'ProcreateHelperWidget/Info.plist' in line and ('PBXBuildFile' in line or 'Copy Bundle Resources' in content[max(0, content.find(line)-200):content.find(line)+200]):
        print(f"Removing: {line.strip()}")
        removed_lines += 1
        continue
    new_lines.append(line)

# Write back the fixed content
with open('Runner.xcodeproj/project.pbxproj', 'w') as f:
    f.write('\n'.join(new_lines))

print(f"Removed {removed_lines} problematic references")
print("Xcode project configuration fixed")
EOF

        python3 fix_project.py
        cd ..
        
    # Install iOS CocoaPods dependencies
    - name: Install iOS Dependencies
      run: |
        cd ios
        pod install --verbose
        cd ..
        
    # Build iOS app for simulator (no signing required)
    - name: Build iOS App for Simulator
      run: |
        flutter build ios --simulator --debug
        
    # Build iOS app for device (attempt without signing)
    - name: Build iOS App for Device (Unsigned)
      run: |
        # Try building for device, but don't fail if it doesn't work
        flutter build ios --release --no-codesign || echo "Device build failed - continuing with simulator build"
        
    # Create IPA files
    - name: Create App Packages
      run: |
        # Create simulator IPA
        if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
          cd build/ios/iphonesimulator
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ProcreateHelperWidget-Simulator.ipa Payload/
          cd ../../..
        fi
        
        # Create device IPA if device build succeeded
        if [ -d "build/ios/iphoneos/Runner.app" ]; then
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ProcreateHelperWidget-Device.ipa Payload/
          cd ../../..
        fi
        
        # List what we created
        find build -name "*.ipa" -type f
        
    # Upload IPA files as artifacts
    - name: Upload App Packages
      uses: actions/upload-artifact@v4
      with:
        name: ProcreateHelperWidget-iOS-Apps
        path: |
          build/ios/iphonesimulator/ProcreateHelperWidget-Simulator.ipa
          build/ios/iphoneos/ProcreateHelperWidget-Device.ipa
        retention-days: 30
        if-no-files-found: ignore
        
    # Upload app bundles as backup
    - name: Upload App Bundles
      uses: actions/upload-artifact@v4
      with:
        name: ProcreateHelperWidget-App-Bundles
        path: |
          build/ios/iphonesimulator/Runner.app
          build/ios/iphoneos/Runner.app
        retention-days: 30
        if-no-files-found: ignore